const universities = [
  {
    id: 1,
    name: "University of Botswana",
    abbreviation: "UB",
    type: "Public",
    location: "Gaborone",
    established: 1982,
    logo: "https://www.ub.bw/sites/default/files/UB-LOGO-2_0.png",
    website: "https://www.ub.bw",
    color: "#1B3A5C",
    description:
      "The University of Botswana is the oldest and largest university in the country. Founded in 1982, it offers undergraduate and postgraduate programmes through faculties such as Business, Education, Engineering and Technology, Health Sciences, Humanities, Science, and Social Sciences. Its main campus is in Gaborone, with additional campuses in Francistown and Maun.",
    programs: [
      "Business & Economics",
      "Education",
      "Engineering & Technology",
      "Health Sciences",
      "Humanities",
      "Medicine",
      "Science",
      "Social Sciences",
    ],
    funFacts: [
      "Alumni include current President Duma Boko (LLB, 1993) and former President Mokgweetsi Masisi, making it the alma mater of multiple Botswana heads of state.",
      "Home to the Okavango Research Institute, which produces globally cited publications on wetland ecosystems and climate resilience in the Okavango Delta.",
      "Ranked 2nd in Southern, Central, and East Africa (excluding South Africa) in the 2026 Times Higher Education World University Rankings.",
    ],
  },
  {
    id: 2,
    name: "Botswana International University of Science and Technology",
    abbreviation: "BIUST",
    type: "Public",
    location: "Palapye",
    established: 2005,
    logo: "https://www.biust.ac.bw/wp-content/uploads/2022/02/real-biust-logo.png",
    website: "https://www.biust.ac.bw",
    color: "#003366",
    description:
      "BIUST was created by an Act of Parliament in 2005 and opened to its first students in 2012. Located in Palapye, it is dedicated to advancing education, research, and innovation in science and technology. The university offers programmes in engineering, earth sciences, information technology, mathematics, and related fields.",
    programs: [
      "Engineering",
      "Earth Sciences",
      "Information Technology",
      "Mathematics",
      "Physics",
      "Chemistry",
    ],
    funFacts: [
      "Built on a massive 2,500-hectare campus in Palapye — roughly the size of 3,500 football fields — making it one of the largest university campuses in Africa.",
      "Leading Botswana's first-ever national satellite project (BOTSAT-1), developed entirely by BIUST engineers with partners including SpaceX and EnduroSat.",
      "Attracts roughly 30% international students and is ranked #1 in Botswana for Engineering in the 2025 Times Higher Education Subject Rankings.",
    ],
  },
  {
    id: 3,
    name: "Botswana Open University",
    abbreviation: "BOU",
    type: "Public",
    location: "Gaborone",
    established: 2017,
    logo: "https://www.bou.ac.bw/templates/it_insightfx/custom/images/logo.jpg",
    website: "https://www.bou.ac.bw",
    color: "#2E7D32",
    description:
      "Botswana Open University succeeded the Botswana College of Distance and Open Learning (BOCODOL) after an Act of Parliament in 2017. The university specialises in open and distance learning, providing flexible study opportunities through regional campuses across Botswana. Programmes cover education, business, agriculture, social sciences, and lifelong learning.",
    programs: [
      "Education",
      "Business",
      "Agriculture",
      "Social Sciences",
      "Distance Learning",
    ],
    funFacts: [
      "Originally Botswana College of Distance and Open Learning (BOCODOL) since 1998, transformed into a full university by an Act of Parliament in 2017.",
      "Its Moodle-based e-learning resources are freely accessible not just to BOU students but to all Junior and Senior Secondary students nationwide.",
      "Operates five regional campuses including Kang — located in the middle of the Kalahari Desert, making education accessible even in remote areas.",
    ],
  },
  {
    id: 4,
    name: "Botswana University of Agriculture and Natural Resources",
    abbreviation: "BUAN",
    type: "Public",
    location: "Gaborone",
    established: 2016,
    logo: "https://www.buan.ac.bw/images/buan_logo_header.png",
    website: "https://www.buan.ac.bw",
    color: "#33691E",
    description:
      "Formerly the Botswana College of Agriculture, BUAN attained university status in 2016. The university focuses on agriculture, animal science, natural resources, food systems, environmental management, and related disciplines while promoting research that supports sustainable development.",
    programs: [
      "Agriculture",
      "Animal Science",
      "Natural Resources",
      "Food Systems",
      "Environmental Management",
      "Veterinary Science",
    ],
    funFacts: [
      "Home to the Meat Industry Training Institute (MITI), Botswana's only dedicated facility for training professionals in the beef industry — crucial in a country where cattle outnumber people.",
      "Maintains a collection of 5,479 flora specimens including trees and economic plants, serving as a key botanical reference for the entire country.",
      "Pioneered climate-smart rice intercropping research in semi-arid Botswana, aiming to reduce the nation's heavy dependence on imported rice.",
    ],
  },
  {
    id: 5,
    name: "Botho University",
    abbreviation: "BU",
    type: "Private",
    location: "Gaborone",
    established: 1997,
    logo: "https://www.bothouniversity.com/assets/logo-BJSiyJQ5.svg",
    website: "https://www.bothouniversity.com",
    color: "#C62828",
    description:
      "Botho University traces its roots to 1997 when it was established as Botho College before attaining university status. It has grown into one of Botswana's leading private universities, offering programmes in business, computing, engineering, education, health sciences, hospitality, and professional studies. The university also has campuses in several African countries.",
    programs: [
      "Business & Accounting",
      "Computing & IT",
      "Engineering",
      "Education",
      "Health Sciences",
      "Hospitality & Tourism",
    ],
    funFacts: [
      "Botswana's largest private tertiary institution, with campuses in four countries: Botswana, Lesotho, Eswatini, and Namibia.",
      "Pioneered the annual 'Linkz ICT Challenge' in 2009, a nationwide competition pitting the best ICT students from UB, BA ISAGO, ABM, and Limkokwing against each other.",
      "Reports a 97% alumni employment rate, attributed to industry-focused training and partnerships with NIIT, Teesside University, and the Open University (UK).",
    ],
  },
  {
    id: 6,
    name: "BA ISAGO University",
    abbreviation: "BA ISAGO",
    type: "Private",
    location: "Gaborone",
    established: 2002,
    logo: "https://www.baisago.ac.bw/sites/default/files/logo%20%2815%29.png",
    website: "https://www.baisago.ac.bw",
    color: "#4A148C",
    description:
      "BA ISAGO University was founded in 2002 and granted full university status in 2015. It operates campuses in Gaborone, Francistown, and Maun, offering programmes in business, education, law, health sciences, social sciences, and information technology at certificate, diploma, undergraduate, and postgraduate levels.",
    programs: [
      "Business & Commerce",
      "Education",
      "Law & Paralegal Studies",
      "Health Sciences",
      "Social Sciences",
      "Information Technology",
    ],
    funFacts: [
      "Founded in Francistown — Botswana's second city — rather than the capital, an unconventional choice when tertiary education outside government institutions was not yet mainstream.",
      "Started with just 50 students and now boasts over 18,500 alumni across three campuses after 25 years of operation.",
      "Founder Odirile Gabasiane spent 7 years as Education Attaché at the Botswana High Commission in London, growing student placements from 300 to over 3,000 before returning home to start the university.",
    ],
  },
  {
    id: 7,
    name: "ABM University College",
    abbreviation: "ABM",
    type: "Private",
    location: "Gaborone",
    established: 1989,
    logo: "https://abm.ac.bw/wp-content/uploads/brizy/imgs/ABM-LOGO-1-270x243x1x0x268x243x1738425810.png",
    website: "https://www.abm.ac.bw",
    color: "#E65100",
    description:
      "ABM University College was founded in 1989 and is among Botswana's longest-established private higher education institutions. It offers programmes in business, accounting, computing, engineering, education, health sciences, hospitality, and related fields, leading to certificate, diploma, degree, and postgraduate qualifications.",
    programs: [
      "Business & Accounting",
      "Computing",
      "Engineering",
      "Education",
      "Health Sciences",
      "Hospitality",
    ],
    funFacts: [
      "Botswana's very first private tertiary institution, established in 1989 — predating most other private colleges by over a decade.",
      "First higher education institution in Botswana to establish an Entrepreneurship Development Centre (2017), with a 24-hour incubation facility.",
      "Offers a BSc in Cybersecurity — one of the newest programs alongside its established business and tourism degrees.",
    ],
  },
  {
    id: 8,
    name: "Gaborone University College of Law and Professional Studies",
    abbreviation: "GUC",
    type: "Private",
    location: "Gaborone",
    established: 2006,
    logo: "https://guc.ac.bw/wp-content/uploads/2026/07/guc_logo_aug_2026-scaled.png",
    website: "https://www.guc.ac.bw",
    color: "#1A237E",
    description:
      "Founded in 2006, GUC provides career-oriented programmes in law, business, accounting, public administration, education, and information technology. The institution is recognised for its emphasis on practical and professional training.",
    programs: [
      "Law",
      "Business & Accounting",
      "Public Administration",
      "Education",
      "Information Technology",
    ],
    funFacts: [
      "Motto is 'Pro Deo et Patria' (For God and Country), with a mission explicitly focused on shaping morally and spiritually responsible graduates.",
      "ISO 9001:2015 certified — a rare quality management credential among Botswana's smaller private institutions.",
      "Offers niche programs not commonly found elsewhere in Botswana, including a Master of Science in Early Childhood Development.",
    ],
  },
  {
    id: 9,
    name: "Limkokwing University of Creative Technology",
    abbreviation: "Limkokwing",
    type: "Private",
    location: "Gaborone",
    established: 2007,
    logo: "https://limkokwing.net/botswana/wp-content/uploads/sites/2/2024/10/Logo-2.png",
    website: "https://www.limkokwing.ac.bw",
    color: "#FF6F00",
    description:
      "Limkokwing University established its Botswana campus in Gaborone in 2007 as part of its international expansion from Malaysia. The university specialises in creative arts, architecture, design, communication, digital media, business, and information technology, attracting students from Botswana and across Southern Africa.",
    programs: [
      "Creative Arts & Design",
      "Architecture",
      "Digital Media",
      "Communication",
      "Business",
      "Information Technology",
    ],
    funFacts: [
      "Botswana campus was the biggest Limkokwing campus globally when it opened in 2008 — surpassing even the Malaysian main campus in Cyberjaya.",
      "Part of a global network spanning 10+ countries across three continents, with students from 160+ countries at the Malaysian campus.",
      "Recognized as the Best Private University in Botswana at the 2015 Botswana Tertiary Education Fair.",
    ],
  },
  {
    id: 10,
    name: "Botswana Accountancy College",
    abbreviation: "BAC",
    type: "Private",
    location: "Gaborone",
    established: 1996,
    logo: "https://www.bac.ac.bw/access%40panel/uploads/image/qr-code-logo.jpg",
    website: "https://www.bac.ac.bw",
    color: "#00695C",
    description:
      "Botswana Accountancy College is a business school established in 1996 with campuses in Gaborone and Francistown. The school specialises in accounting, finance, business, management, hospitality, taxation, leisure, and ICT. Over 2,000 graduates have completed various disciplines including entrepreneurship, computing, and professional courses.",
    programs: [
      "Accounting & Finance",
      "Business & Management",
      "Hospitality",
      "Taxation",
      "ICT",
    ],
    funFacts: [
      "Established as a joint venture between the Ministry of Finance, Debswana Diamond Company, and the Botswana Institute of Accountants — specifically to reduce reliance on expatriate accountants.",
      "In 2000, became one of only two colleges outside Europe to be awarded 'CIMA Learning through Partnership' status from the Chartered Institute of Management Accountants.",
      "Now has over 20,000 alumni, with degree programs accredited by three UK universities including Sheffield Hallam and the University of Derby.",
    ],
  },
  {
    id: 11,
    name: "Boitekanelo College",
    abbreviation: "BC",
    type: "Private",
    location: "Gaborone",
    established: 2007,
    logo: "https://www.boitekanelo.ac.bw/assets/website/images/logo/logo-white.png",
    website: "https://www.boitekanelo.ac.bw",
    color: "#880E4F",
    description:
      "Boitekanelo College was founded in 2007 and is one of the best medical-focused institutions in Botswana. The college offers a wide range of health-related courses including Clinical Technology, Pharmacy, Emergency Medical Care, Counselling, Community Development, and Occupational Health and Safety.",
    programs: [
      "Clinical Technology",
      "Pharmacy",
      "Emergency Medical Care",
      "Counselling",
      "Community Development",
      "Occupational Health & Safety",
    ],
    funFacts: [
      "Founded specifically to train Healthcare Assistants during the height of the HIV/AIDS pandemic — a direct response to Botswana's most urgent health crisis.",
      "Claims a remarkable 98% pass rate and 70% job placement within six months of graduation, making it one of the most employment-effective colleges in the country.",
      "Offers unique programs rarely found in Botswana, including BSc in Audiology, Speech and Language Therapy, and Occupational Therapy.",
    ],
  },
  {
    id: 12,
    name: "New Era College",
    abbreviation: "NEC",
    type: "Private",
    location: "Gaborone",
    established: 2008,
    logo: "https://www.neweracollege.ac.bw/assets/images/new-logowb.png",
    website: "https://www.neweracollege.ac.bw",
    color: "#0277BD",
    description:
      "New Era College was established in 2008 and is fully accredited by the Botswana Qualifications Authority. The college offers programmes in engineering disciplines such as Construction, Electrical, Electronic, and Telecommunications Engineering, as well as Tourism and Hospitality programmes.",
    programs: [
      "Construction Engineering",
      "Electrical & Electronic Engineering",
      "Telecommunications Engineering",
      "Tourism & Hospitality",
    ],
    funFacts: [
      "Runs a national STEM Kits program selling DIY electronics/robotics kits to learners aged 8 and up, rolling out Tinkering Labs in schools across Botswana.",
      "Hosts an annual National STEM Hackathon (now in its 6th year) in partnership with the Mathematical Association of Botswana.",
      "Developed a SMART Water Tank and SMART Greenhouse using sensor automation — showcased at the national Month of Science launch as locally built innovation.",
    ],
  },
];
